#!/bin/bash

generate_password() {
    symbols="!@#$%^&*()_-+=<>?/"
    uppercase="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    lowercase="abcdefghijklmnopqrstuvwxyz"
    numbers="0123456789"
    
    all_chars="${symbols}${uppercase}${lowercase}${numbers}"
    
    length="$1"
    
    if [ -z "$length" ]; then
        length=12
    fi
    
    password=""
    
    for (( i=0; i<length; i++ )); do
        random_char=${all_chars:$((RANDOM%${#all_chars})):1}
        
        password="${password}${random_char}"
    done
    
    echo "$password"
}
